// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqkzAvNYxkT9-NS4e9NOnPYdkwhGT5sNI',
    appId: '1:483965343668:web:a931cf0b58c59b9c0344e1',
    messagingSenderId: '483965343668',
    projectId: 'tewipr',
    authDomain: 'tewipr.firebaseapp.com',
    storageBucket: 'tewipr.firebasestorage.app',
    measurementId: 'G-2S0ZLS5K2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZIAiDFz1poePzI-8EfegLyPDBC5iiNg',
    appId: '1:483965343668:android:11dc5bfebcba75990344e1',
    messagingSenderId: '483965343668',
    projectId: 'tewipr',
    storageBucket: 'tewipr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZnQE7-l4jL30J-mL3YsUKQaNJMhTfxaU',
    appId: '1:483965343668:ios:503d555f767fec2f0344e1',
    messagingSenderId: '483965343668',
    projectId: 'tewipr',
    storageBucket: 'tewipr.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZnQE7-l4jL30J-mL3YsUKQaNJMhTfxaU',
    appId: '1:483965343668:ios:503d555f767fec2f0344e1',
    messagingSenderId: '483965343668',
    projectId: 'tewipr',
    storageBucket: 'tewipr.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqkzAvNYxkT9-NS4e9NOnPYdkwhGT5sNI',
    appId: '1:483965343668:web:ba38256e083cc6d70344e1',
    messagingSenderId: '483965343668',
    projectId: 'tewipr',
    authDomain: 'tewipr.firebaseapp.com',
    storageBucket: 'tewipr.firebasestorage.app',
    measurementId: 'G-W2VE809F2L',
  );
}
